"""text

Revision ID: 04de28c1a166
Revises: 45733f23a329
Create Date: 2021-10-26 08:51:06.039901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04de28c1a166'
down_revision = '45733f23a329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=1400),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=1400),
               nullable=True)
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
