"""subtitle

Revision ID: 19494a34a338
Revises: 04de28c1a166
Create Date: 2021-10-26 09:40:42.894152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19494a34a338'
down_revision = '04de28c1a166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('subtitle', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'subtitle')
    # ### end Alembic commands ###
